language: python
install:
  - make install
  - python manage.py db upgrade
# command to run tests
script:
  - make tests
notifications:
  slack:
    rooms:
      - ucu-datascience:$SLACK_TOKEN
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - "Build details: %{message}"
