language: python
env:
  - FLASK_APP=trainer.py
install:
  - make install
  - flask db upgrade
# command to run tests
script:
  - flask utils test
notifications:
  slack:
    if: branch = master
    rooms:
      - ucu-datascience:4Y7tTkbcnVJLy7O8ClUFTt2K
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - "Build details: %{message}"
