language: python
env:
  - FLASK_APP=manage.py
install:
  - make install
  - flask db upgrade
# command to run tests
script:
  - flask utils test
notifications:
  slack: ucu-datascience:4Y7tTkbcnVJLy7O8ClUFTt2K
