version: "2"

networks:
  model-trainer-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:latest"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - model-trainer-tier
  # model-trainer-app:
  #   build: ./
  #   ports:
  #     - 80:5000
  #   networks:
  #     - model-trainer-tier
